options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |

        echo "SHA del commit: $COMMIT_SHA"
        echo "Nombre de la rama: $BRANCH_NAME"
        COMMIT_MSG=$(git log -1 $COMMIT_SHA --pretty=%B)
        echo "Mensaje del commit: $COMMIT_MSG"


        if [[ "$BRANCH_NAME" == "develop" ]] || [[ "$COMMIT_SHA" == "deploid_develop" ]]; then
          echo "Rama es develop o commit es 'deploid_develop'. Ejecutando despliegue..."

          echo "Limpiando carpeta remota..."
          gcloud compute ssh cloud-build \
            --zone=us-central1-f \
            --command="rm -rf /var/www/html/*"

          echo "Copiando nuevo código..."
          gcloud compute scp --recurse * cloud-build:/var/www/html --zone=us-central1-f
        else
          echo "No es la rama develop ni el commit es 'deploid_develop'. Saltando pasos."
        fi
