options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        if [[ "$BRANCH_NAME" == "develop" ]]; then
          echo "Rama es develop. Ejecutando despliegue..."

          echo "Limpiando carpeta remota..."
          gcloud compute ssh cloud-build \
            --zone=us-central1-f \
            --command="rm -rf /var/www/html/*"

          echo "Copiando nuevo código..."
          gcloud compute scp --recurse * cloud-build:/var/www/html --zone=us-central1-f
        else
          echo "No es la rama develop. Saltando pasos."
        fi
