name: Borrar tags dev-*

on:
  workflow_dispatch:
  schedule:
      - cron: '0 23 * * 1-5'  # Lunes a viernes a las 19:00 hora Chile (UTC-4)
jobs:
  delete-dev-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Mostrar tags dev-*
        run: |
          echo "Tags encontrados con patrón dev-*:"
          git tag -l "dev-*"

      - name: Eliminar tags dev-* en remoto
        run: |
          for tag in $(git tag -l "dev-*"); do
            echo "Eliminando tag remoto: $tag"
            git push origin ":refs/tags/$tag"
          done
