name: 🚀 Deploid Manual

on:
  workflow_dispatch:

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Esperar aprobación
        uses: peter-evans/wait-for-approval@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: andystefano  # GitHub usernames que pueden aprobar
          timeout-minutes: 60
          issue-title: "Aprobación requerida para deploy"
          body: "Por favor aprueba este despliegue."

  deploy:
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar despliegue
        run: echo "Deploy a producción..."